### ISSUE TITLE
Agregar mas informacion sobre lo que te apasiona 

### ISSUE THREAD

**Issue by GabrielIacomini** [pdepviernestm/2024-presentacion-VEBravo#1]
Muy buena presentación, estaría bueno que nos cuentes algo mas sobre vos, quizá algún dato que se pueda tener en cuenta y que sume a la hora de formar grupos de trabajo.

**Comment by ValentinEnnioBravo** [comment]
Ah, dale, ahora lo agrego. Gracias.
